name: Build Proxychains-NG RPMs with Spec File

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ['almalinux:9', 'almalinux:8']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Proxychains-NG RPM
      run: |
        docker pull ${{ matrix.os }}
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ${{ matrix.os }} /bin/bash -c "
          # Copy build script into the container
          cp /workspace/build-proxychains-ng.sh /tmp &&
          chmod +x /tmp/build-proxychains-ng.sh &&
          # Run build script
          /tmp/build-proxychains-ng.sh
        "

    - name: Display proxychains-ng qpl info
      run: |
        echo "Displaying proxychains-ng qpl info:"
        cat ${{ github.workspace }}/proxychains-ng-qpl-output.log

    - name: Display proxychains-ng changelog info
      run: |
        echo "Displaying proxychains-ng changelog info:"
        cat ${{ github.workspace }}/proxychains-ng-changelog-output.log

    - name: Display proxychains-ng yum info
      run: |
        echo "Displaying proxychains-ng yum info:"
        cat ${{ github.workspace }}/proxychains-ng-yuminfo-output.log

    - name: Inspect RPM contents
      run: |
        ls -lah rpms/
        rpm -qpl rpms/proxychains-ng-*.rpm

    - name: Set custom artifact name
      run: |
        if [[ '${{ matrix.os }}' == 'almalinux:8' ]]; then
          echo "ARTIFACT_NAME=proxychains-ng-rpm-almalinux-8" >> $GITHUB_ENV
        else
          echo "ARTIFACT_NAME=proxychains-ng-rpm-almalinux-9" >> $GITHUB_ENV
        fi

    - name: Upload RPM
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: rpms/
        if-no-files-found: warn
        retention-days: 5
